name: Golang CI Workflow

on:
  workflow_call:
    inputs:
      GO_VERSION:
        required: false
        type: string
        default: "1.18"
      TESTS_LOCATION:
        required: false
        type: string
        default: "./..."

jobs:
  test:
    name: Test with coverage and send coverage report to coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code / lint code / install dependencies for goveralls
        uses: uc-cdis/.github/.github/actions/golang-ci@master
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=./profile.cov -service=github
