name: Build Image and Push to Quay

on:
  workflow_call:
    inputs:
      DOCKERFILE_LOCATION:
        required: false
        type: string
        default: "./Dockerfile"
      AWS_REGION:
        required: false
        type: string
        default: "us-east-1"
      

jobs:
  ci:
    name: Build Image and Push to Quay
    runs-on: ubuntu-latest
    steps:
      # https://github.com/docker/login-action#aws-public-elastic-container-registry-ecr
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ inputs.AWS_REGION }}

      # https://github.com/docker/login-action#quayio
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: image-gh-action
          tags: v1
          containerfiles: |
            ${{ inputs.DOCKERFILE_LOCATION }}

      - name: Set Variables
        shell: bash
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_REF_NAME | sed 's/\//_/')" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}' | sed -e 's/:refs//')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.DOCKERFILE_LOCATION }}
          platforms: linux/amd64,linux/arm64
          push: true
          # https://docs.github.com/en/actions/learn-github-actions/expressions#format
          tags: |
            ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
            quay.io/cdis/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=quay.io/cdis/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
          cache-to: type=inline
