name: Build Image and Push to Quay

on:
  workflow_call:
    inputs:
      DOCKERFILE_LOCATION:
        required: false
        type: string
        default: "./Dockerfile"
      AWS_REGION:
        required: false
        type: string
        default: "us-east-1"
      ORG_AND_REPO_NAME:
        required: false
        type: string
        default: ${{ GITHUB_REPOSITORY }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      QUAY_USERNAME:
        required: true
      QUAY_ROBOT_TOKEN:
        required: true
      

jobs:
  ci:
    name: Build Image and Push to Quay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: image-gh-action
          tags: v1
          containerfiles: |
            ${{ inputs.DOCKERFILE_LOCATION }}

      # https://github.com/docker/login-action#aws-public-elastic-container-registry-ecr
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ inputs.AWS_REGION }}

      # https://github.com/docker/login-action#quayio
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Image Tag as Variable
        shell: bash
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_REF_NAME | sed 's/\//_/')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.DOCKERFILE_LOCATION }}
          platforms: linux/amd64,linux/arm64
          push: true
          # https://docs.github.com/en/actions/learn-github-actions/expressions#format
          tags: |
            ${{ inputs.ORG_AND_REPO_NAME }}:${{ IMAGE_TAG }}
            quay.io/${{ inputs.ORG_AND_REPO_NAME }}:${{ IMAGE_TAG }}
          cache-from: type=registry,ref=quay.io/cdis/covid19-notebook-etl:${{ steps.extract_branch.outputs.branch }}
          cache-to: type=inline
