name: Run unit tests
on: workflow_call
  inputs:
  SETUP_SCRIPT_LOCATION:
    description: 'A URL identifying a Bash script that can run commands needed for service-specific test setup'
    required: true
    
env: 
  PGPASSWORD: postgres

jobs:
  run_tests:
    runs-on: ubuntu-latest
    
    #Defining the Postgres DB service we will need to run the unit tests
    services:
      postgres:
        image: postgres:13-bullseye
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Install poetry
        run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            poetry install -vv   
      - name: Service specific setup
        run: |
            curl -sSL $INPUT_SETUP_SCRIPT_LOCATION | bash
      - name: Run test
        run: | 
          source $HOME/.poetry/env
          poetry run pytest -vv --cov=fence --cov-report xml tests
      - name: Clean up from test
        run: |
          pip3 install codacy-coverage
          python-codacy-coverage -r coverage.xml
