name: Security Pipeline
on:
  pull_request:
    - opened
    - reopened
    - ready_for_review
    - synchronize
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
        uses: RobertFischer/detect-secrets-action@v2.0.0
