name: Security Pipeline

on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
   name: Super-Linter
    uses: uc-cdis/.github/.github/workflows/lint.yaml@master

   name: Easy detect-secrets
    uses: RobertFischer/detect-secrets-action@v2.0.0

   name: CodeQl
    uses: uc-cdis/.github/.github/workflows/codeql-scan.yaml@master
