name: Security Pipeline
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  call-workflow-1-in-local-repo:
   uses: RobertFischer/detect-secrets-action@v2.0.0
  call-workflow-2-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/lint.yaml@master
  call-workflow3-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/codeql-scan.yaml@master
