name: Security Pipeline
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  call-workflow-1-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/lint.yaml@SDO-13-ci-using-gh-actions
  call-workflow2-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/codeql-scan.yaml@master
  secrets-detection:
    runs-on: 'ubuntu-latest'
    steps:
      - name: secrets detect
        uses: RobertFischer/detect-secrets-action@v2.0.0
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "poetry.lock"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: uc-cdis/.github/.github/actions/snykcli.yaml@sdo-13-ci-using-gh-actions
