name: Security Pipeline
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  call-workflow-2-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/lint.yaml@SDO-13-ci-using-gh-actions
  call-workflow3-in-local-repo:
   uses: uc-cdis/.github/.github/workflows/codeql-scan.yaml@master
  secrets-detection:
    runs-on: 'ubuntu-latest'
    steps:
      - name: secrets detect
        uses: RobertFischer/detect-secrets-action@v2.0.0
