name: Security Pipeline
on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  reusable_workflow_job:
    steps:
        uses: RobertFischer/detect-secrets-action@v2.0.0
