name: Security Pipeline
on:
  pull_request:
    - opened
    - reopened
    - ready_for_review
    - synchronize
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  Secure and Lint
    steps:
        name: Easy detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
